// <auto-generated />
namespace A4Aero.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddJoinedOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddJoinedOn));
        
        string IMigrationMetadata.Id
        {
            get { return "202002150501045_AddJoinedOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
